### ISSUE TITLE
how can I add braker-generated UTR features into TSEBRA out ?

### ISSUE THREAD

**Issue by tinyhys** [Gaius-Augustus/TSEBRA#10]
Hi dear developers,
I have run BRAKER with --addUTR=on, but the structure of braker_utr.gtf with UTR feature is different from braker.gtf, thus I have no idea how to add UTRs to the final annotation using TSEBRA. 
Could you please give me some suggestions?
best !

**Comment by LarsGab** [comment]
Hi, 

the UTR-features of the selected transcripts should already be included in the result of TSEBRA. Could you send me an example, where the UTR features are removed by TSEBRA?

Note that the UTR features have no impact on the selection and filtering process of TSEBRA. 

Best, Lars

**Comment by tinyhys** [comment]
Thanks for your reply! Maybe I have found what going wrong -- the fix_gtf_ids.py add a space in the IDs of UTRs.
![image](https://user-images.githubusercontent.com/37066354/139679984-264c06e5-d389-4df4-99c5-ce17f6490f06.png)

And after I use sed to delete the space, TSEBRA seems to be working with a few format error
![image](https://user-images.githubusercontent.com/37066354/139680739-890e7649-9bcd-4e7c-bd3c-662d67a7323a.png)

**Comment by LarsGab** [comment]
Thanks for bringing this to my attention! 
I fixed these errors with the newest commits, and it should work now.
Best, Lars

**Comment by tinyhys** [comment]
> Thanks for bringing this to my attention! I fixed these errors with the newest commits, and it should work now. Best, Lars

Sorry for late reply. Many thanks for your work!  I have tested the new scripts on my data any met a problem with the rename_gtf.py as the pic shows. After renaming, gene numbers increased from 23414 to 26179. I have not detected what was going wrong yet.
![image](https://user-images.githubusercontent.com/37066354/140675295-ce2bd295-5cac-4749-8f90-16bb2c51f9cf.png)
![image](https://user-images.githubusercontent.com/37066354/140675326-fe816a63-b1d8-4301-875a-3de6056c93ee.png)

**Comment by LarsGab** [comment]
Hi, there might be nothing wrong here. The original file probably does not list a gene feature line for each gene. The `rename_gtf.py` adds these into the file. 
If you are not sure if this is the case, you can send me the files and I'll take a look.
Best, Lars

**Comment by tinyhys** [comment]
[tsebra.gtf1.gz](https://github.com/Gaius-Augustus/TSEBRA/files/7496979/tsebra.gtf1.gz)

Here is my file generated by TSEBRA. Thanks a lot !

**Comment by tinyhys** [comment]
And I think the 23414 is the correct number because the BUSCO reaches 97% and 26179 genes only increase dups.

**Comment by tinyhys** [comment]
Maybe I have found something helpful to locate the issue, these 'not unique' EERORs are caused by the repeat transcript IDs

![image](https://user-images.githubusercontent.com/37066354/140745109-1ac59e59-b7b8-45a9-831c-3c2559cecae8.png)

**Comment by tinyhys** [comment]
Maybe the issue is caused by the similar transcript ID?

![image](https://user-images.githubusercontent.com/37066354/140746532-71c7b56a-0377-4a5c-a9be-20737d9a41f3.png)

**Comment by tinyhys** [comment]
After renaming,  the two transcripts which used to belong to one gene became two genes. And their coordinates overlap. 

![image](https://user-images.githubusercontent.com/37066354/140751116-18617e0c-6423-4e33-bc39-27feb5b7dfb1.png)

**Comment by LarsGab** [comment]
Thanks again for your feedback! I found the error, there was an empty space in some strand columns and TSEBRA believed that for example '+' and '+ ' weren't on the same strand. It is fixed now and it showed work.
Best, Lars

**Comment by tinyhys** [comment]
So many thanks for your effective and efficient work! 
Best ~
