### ISSUE TITLE
Non-overlapping isoforms

### ISSUE THREAD

**Issue by alexcorm** [Gaius-Augustus/TSEBRA#16]
Hi,

I've combined RNA-seq and proteins evidences from Braker with Tsebra using default configuration file with great result. By manually inspecting the annotations, I found one particular case for which Tsebra produces a single gene but with 2 non-overlapping isoforms when it should produce 2 annotations.

<img width="1360" alt="Capture d’écran 2022-05-31 à 14 56 15" src="https://user-images.githubusercontent.com/8090899/171182380-fc281e11-1ad6-43f2-ac3c-7f3d42026ac6.png">

Strangely, for similar cases (one braker1 gene and multiples braker2 genes), Tsebra produces a correct result.

Thanks,
Alex

**Comment by LarsGab** [comment]
I close this issue since all questions have been answered or it has been inactive for a long time.
