### ISSUE TITLE
Selecting protein sequences after merging annotation sets; what do the anno1 and anno2 prefixes mean in gtf file?

### ISSUE THREAD

**Issue by robertwhbaldwin** [Gaius-Augustus/TSEBRA#21]
Hi,
Thanks for this great tool. I ran it using a case similar to the example found on this github page and got the gtf file. For each transcript in the gtf file I then wanted to pull out the corresponding amino acid sequence from the augustus_hints.aa files in the braker1_out and braker2_out working folders. I noticed that in the gtf file the transcript ids are prefixed with anno1 or anno2. 

For example I have two transcript with the following names:
anno2.g23134.t1
anno1.g27019.t1

If I go to the braker1_out folder and search for an amino acid sequence called g23134.t1 in the augustus.hints.aa  it's there.
But it's also there if I search for it in the augustus.hints.aa file in the braker2_out folder. 

I was thinking that anno1 means the corresponding sequence is found in the braker1 folder and anno2 in the braker2 folder since I passed these files to TSEBRA in that order. Not sure at the moment.

Can anyone clear this up? Thanks. I just need to know what protein sequence to pull out for each transcript in the merged gtf file. It doesn't seem to be something that TSEBRA will do for you. 

Thnaks - Robert

**Comment by salvatierra8** [comment]
Greetings,

I don't want to open a new thread cuz my question is related to this; perhaps it's obvious but i want to be sure, the protein sequences to be used using  `gtf2aa genome.fa tsebra.gtf aa_seqs.fa` is a concatenated file containing the proteins from both outputs, correct?
