### ISSUE TITLE
where is the gff2aa.pl script?

### ISSUE THREAD

**Issue by joleneyue** [Gaius-Augustus/TSEBRA#30]
Dear Developer,

i used TSEBRA to predict the genes and get the gtf file eventually.

 i would like to extract the protein sequences from the gtf file, shall i use script gff2aa.pl, however, i do not find it anywhere under the tsebra installation guide.

Could you let me know the answer?

thanks A lot!
Cheers,
Jolene

**Comment by bijendrabio** [comment]
@joleneyue check Augustus utilities script folder
