### ISSUE TITLE
`--ignore_tx_phase` on branch long_reads

### ISSUE THREAD

**Issue by gbdias** [Gaius-Augustus/TSEBRA#38]
Hi @LarsGab

Is there a way we can have the --ignore_tx_phase option in the long_reads branch as well?

**Comment by LarsGab** [comment]
Hi,

I added the `--ignore_tx_phase` option to the long_reads branch. It works the same as in the main branch. 

Best, Lars

**Comment by gbdias** [comment]
Thanks @LarsGab !
