### ISSUE TITLE
TSEBRA generates gtf file without 'gene'  meta-feature in the third column

### ISSUE THREAD

**Issue by dieunelderilus** [Gaius-Augustus/TSEBRA#4]
Hello TSEBRA developer,

I run  TSEBRA using  the  small example of dataset located at  **_'example/'_** folder  and I see that there is a big difference between the third column of the of input  and the output gtf file. The gtf file generated by tsebra misses the _'gene'_  meta-feature in the third column.
Here is how look the third column of the braker.gtf file:

```
 awk '{print $3}' braker1_results/braker.gtf | sort -u
CDS
exon
**gene**
intron
start_codon
stop_codon
transcript
```
Here is  how looks the third column  of the  tsebra output:
```
awk '{print $3}' braker_combined.gtf | sort -u
CDS
exon
intron
start_codon
stop_codon
transcript
```
Here the **gene__** meta-feature is is not present in the tsebra output.  Please how this could be fixed ?  how I can fix this formatting issue a way to have the  _**gene**_ tag in the third column of tsebra output

Thank you

**Comment by LarsGab** [comment]
Hi @dieunelderilus,

thank you for pointing this out. I added the gene feature to the output of TSEBRA in the latest commit (f126c49bb85f7df31ceb4268a08a4e780924cfc6) and included it in the latest release ([TSEBRA v1.0.2](https://github.com/Gaius-Augustus/TSEBRA/releases/tag/v1.0.2)).

Best,
Lars
