### ISSUE TITLE
The Genemark and Augustus profile from TSEBRA

### ISSUE THREAD

**Issue by wyim-pgl** [Gaius-Augustus/TSEBRA#5]
Dear TSEBRA,
Hello, I successfully finished BRAKER and results were merged with TSEBRA.
Is there anyway to get Genemark and Augustus ab initio profile for MAKER?
Thanks.

**Comment by LarsGab** [comment]
Hi,

sorry for the late answer. The result of TSEBRA doesn't include only transcripts that are supported by extrinsic evidence, at least in default configuration. Therefore, I don't think it is possible to get ab initio profiles for MAKER from it. However, I'm not that familiar with MAKER, what exactly do you need from the TSEBRA output? 

Best, Lars

**Comment by LarsGab** [comment]
I close this issue since all questions have been answered or it has been inactive for a long time.
