### ISSUE TITLE
detailed document for the configure setting 

### ISSUE THREAD

**Issue by sotuamax** [Gaius-Augustus/TSEBRA#8]
Hi,

I was wondering if there is a detailed document to clarify each argument and its function in the configure file. It is hard to understand what the setting means in your default file. 

Many thanks. 

Meiyuan

**Comment by conchoecia** [comment]
Something simple like this on the README.md would be helpful!

```
P = protein hints
E = RNA-seq hints
C = ?
M = ?
```

**Comment by LarsGab** [comment]
Hi, thanks for the suggestion. I will add such a section for the hint sources of BRAKER to the Documentation. 
Until then:
```
E = RNA-seq hints
M = manual hints, BRAKER requires that these hints are used.
C = protein hints from proteins with a 'high' spliced alignment score.
P = protein hints from proteins that have a 'good' spliced alignment score, 
     but that is lower than the score from the ones in 'C'. 
```

Best, Lars

**Comment by LarsGab** [comment]
I am closing this topic as the documentation has been changed accordingly.

**Comment by conchoecia** [comment]
Thanks for the update, @LarsGab!
